-- MySQL Script generated by MySQL Workbench
-- Mon Nov 23 19:53:15 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema merch
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema merch
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `merch` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `merch` ;

-- -----------------------------------------------------
-- Table `merch`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `merch`.`products` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(45) NULL COMMENT '',
  `description` TEXT NULL COMMENT '',
  `price` DECIMAL(5,2) NULL COMMENT '',
  `created_at` DATETIME NULL COMMENT '',
  `updated_at` DATETIME NULL COMMENT '',
  `category` VARCHAR(45) NULL COMMENT '',
  `img` VARCHAR(225) NULL COMMENT '',
  `sku` INT NULL COMMENT '',
  `prod_status` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `merch`.`customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `merch`.`customers` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `billing_first` VARCHAR(45) NULL COMMENT '',
  `billing_last` VARCHAR(45) NULL COMMENT '',
  `billing_address` VARCHAR(225) NULL COMMENT '',
  `billing_city` VARCHAR(45) NULL COMMENT '',
  `billing_state` VARCHAR(45) NULL COMMENT '',
  `billing_zip` INT NULL COMMENT '',
  `shipping_first` VARCHAR(45) NULL COMMENT '',
  `shipping_last` VARCHAR(45) NULL COMMENT '',
  `shipping_address` VARCHAR(225) NULL COMMENT '',
  `shipping_city` VARCHAR(45) NULL COMMENT '',
  `shipping_state` VARCHAR(45) NULL COMMENT '',
  `shipping_zip` INT NULL COMMENT '',
  `email` VARCHAR(225) NULL COMMENT '',
  `cardholder_name` VARCHAR(225) NULL COMMENT '',
  `cc_number` INT NULL COMMENT '',
  `exp` INT NULL COMMENT '',
  `cvc` INT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `merch`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `merch`.`orders` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `created_at` VARCHAR(45) NULL COMMENT '',
  `customer_id` INT NOT NULL COMMENT '',
  `status` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_orders_customers1_idx` (`customer_id` ASC)  COMMENT '',
  CONSTRAINT `fk_orders_customers1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `merch`.`customers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `merch`.`orders_has_products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `merch`.`orders_has_products` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `order_id` INT NOT NULL COMMENT '',
  `product_id` INT NOT NULL COMMENT '',
  `qty` INT NULL COMMENT '',
  PRIMARY KEY (`id`, `order_id`, `product_id`)  COMMENT '',
  INDEX `fk_orders_has_products_products1_idx` (`product_id` ASC)  COMMENT '',
  INDEX `fk_orders_has_products_orders1_idx` (`order_id` ASC)  COMMENT '',
  CONSTRAINT `fk_orders_has_products_orders1`
    FOREIGN KEY (`order_id`)
    REFERENCES `merch`.`orders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_has_products_products1`
    FOREIGN KEY (`product_id`)
    REFERENCES `merch`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `merch`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `merch`.`admin` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `admin_email` VARCHAR(225) NULL COMMENT '',
  `password` VARCHAR(225) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
